#!/bin/bash

function download() {
    url=$1
    dest=$2

    response=$(curl -X GET ${url} -o -)
    format=$(echo ${response} | jq -r .format)
    if [ "${format}" = "base64" ] ; then
        echo ${response} | jq -j .content | base64 -d > $dest
    elif [ "${format}" = "text" ] ; then
        echo ${response} | jq -j .content > $dest
    else
        echo "Format ${format} of file ${dest} not supported"
        echo ${response} | jq -j .content > $dest
    fi
}

notebook_created="no"

function get_notebook() {
    ## Creates a new notebook if needed. Sets flag to delete if
    ## notebook was re-created.
    apiurl=$1
    sessionid=$2
    serviceid=$3
    svcinfo=`curl --silent -X GET "${apiurl}/${serviceid}" -H  "accept: application/json"`
    if [ $(echo ${svcinfo} | jq -j .sessionId) = "${sessionid}" ] ; then
        return ## NOTEBOOK_URL unchanged.
    fi
    
    svcinfo=`curl --silent -X POST "${apiurl}" -H  "accept: application/json" \
                  -H  "Content-Type: application/json" -d "{\"sessionId\":\"${sessionid}\"}"`
    notebook_created="yes"
    
    svcurl=`echo ${svcinfo} | jq -j .serviceURL`
    if [ "${svcurl}" = "null" ] ; then
        echo "Session ${sessionid} no longer exists. Cannot download data."
        exit 1
    fi

    SERVICE_ID=`echo ${svcinfo} | jq -j .id`
    echo "Wait for service ${SERVICE_ID} to be re-created at ${svcurl}."
    while ! curl --silent -IL -X GET ${svcurl} | grep "200 OK" ; do
        sleep 5
    done
    NOTEBOOK_URL=${svcurl}
}

function delete_notebook() {
    apiurl=$1
    if [ "${notebook_created}" = "yes" ] ; then
        curl -X DELETE "${apiurl}/${SERVICE_ID}" -H  "accept: */*"
    fi
}

function download_working_dir_data() {
    if [ ! -e download_filelist.dat ] ; then
        echo "Nothing to download from working dir."
        return
    fi
    apiurl=$1
    for file in `cat download_filelist.dat` ; do
        download ${apiurl}/${file} ${HOME}/${file}
    done
}

conda install -y -c conda-forge curl jq || exit 1


# =======================================================
# Everything below here is generated by the snapshot job:
# =======================================================
NOTEBOOK_URL=https://swirrl.climate4impact.eu/swirrl/jupyter/4f040adc-7e53-4cf3-b7b2-8168e4588b11
SERVICE_ID=4f040adc-7e53-4cf3-b7b2-8168e4588b11
get_notebook https://swirrl.climate4impact.eu/swirrl-api/v1.0/notebook 2ea20976-7d5c-4ad5-9e46-9b430c6ce6fa 4f040adc-7e53-4cf3-b7b2-8168e4588b11
mkdir -p ~/data/staginghistory/stage.00014
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc ~/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_Amon_CMCC-ESM2_ssp585_r1i1p1f1_gn_201501-210012.nc ~/data/staginghistory/stage.00014/tas_Amon_CMCC-ESM2_ssp585_r1i1p1f1_gn_201501-210012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc ~/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc ~/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_209501-210012.nc ~/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_209501-210012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc ~/data/staginghistory/stage.00014/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc ~/data/staginghistory/stage.00014/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_Amon_BCC-CSM2-MR_historical_r1i1p1f1_gn_185001-201412.nc ~/data/staginghistory/stage.00014/tas_Amon_BCC-CSM2-MR_historical_r1i1p1f1_gn_185001-201412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc ~/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc ~/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_185001-194912.nc ~/data/staginghistory/stage.00014/tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_185001-194912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_203501-205412.nc ~/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_203501-205412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_Amon_BCC-CSM2-MR_ssp585_r1i1p1f1_gn_201501-210012.nc ~/data/staginghistory/stage.00014/tas_Amon_BCC-CSM2-MR_ssp585_r1i1p1f1_gn_201501-210012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20230101-20231231.nc ~/data/staginghistory/stage.00014/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20230101-20231231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_Amon_ACCESS-CM2_ssp585_r1i1p1f1_gn_201501-210012.nc ~/data/staginghistory/stage.00014/tas_Amon_ACCESS-CM2_ssp585_r1i1p1f1_gn_201501-210012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20240101-20241231.nc ~/data/staginghistory/stage.00014/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20240101-20241231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_195001-201412.nc ~/data/staginghistory/stage.00014/tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_195001-201412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00014/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc ~/data/staginghistory/stage.00014/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00014/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_205501-207412.nc ~/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_205501-207412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00014/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_Amon_GFDL-ESM4_ssp585_r1i1p1f1_gr1_201501-210012.nc ~/data/staginghistory/stage.00014/tas_Amon_GFDL-ESM4_ssp585_r1i1p1f1_gr1_201501-210012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc ~/data/staginghistory/stage.00014/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_Amon_GFDL-ESM4_historical_r1i1p1f1_gr1_195001-201412.nc ~/data/staginghistory/stage.00014/tas_Amon_GFDL-ESM4_historical_r1i1p1f1_gr1_195001-201412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc ~/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/swirrl_fileinfo.json ~/data/staginghistory/stage.00014/swirrl_fileinfo.json
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_Amon_INM-CM5-0_ssp585_r1i1p1f1_gr1_201501-210012.nc ~/data/staginghistory/stage.00014/tas_Amon_INM-CM5-0_ssp585_r1i1p1f1_gr1_201501-210012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_Amon_ACCESS-CM2_historical_r1i1p1f1_gn_185001-201412.nc ~/data/staginghistory/stage.00014/tas_Amon_ACCESS-CM2_historical_r1i1p1f1_gn_185001-201412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc ~/data/staginghistory/stage.00014/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_Amon_CMCC-ESM2_historical_r1i1p1f1_gn_185001-201412.nc ~/data/staginghistory/stage.00014/tas_Amon_CMCC-ESM2_historical_r1i1p1f1_gn_185001-201412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00014/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc ~/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_Amon_GFDL-ESM4_historical_r1i1p1f1_gr1_185001-194912.nc ~/data/staginghistory/stage.00014/tas_Amon_GFDL-ESM4_historical_r1i1p1f1_gr1_185001-194912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_207501-209412.nc ~/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_207501-209412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc ~/data/staginghistory/stage.00014/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc ~/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc ~/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc ~/data/staginghistory/stage.00014/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc
mkdir -p ~/data/staginghistory/stage.00013
ln ~/data/staginghistory/stage.00014//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc ~/data/staginghistory/stage.00013/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc
ln ~/data/staginghistory/stage.00014//tas_Amon_CMCC-ESM2_ssp585_r1i1p1f1_gn_201501-210012.nc ~/data/staginghistory/stage.00013/tas_Amon_CMCC-ESM2_ssp585_r1i1p1f1_gn_201501-210012.nc
ln ~/data/staginghistory/stage.00014//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc ~/data/staginghistory/stage.00013/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc
ln ~/data/staginghistory/stage.00014//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc ~/data/staginghistory/stage.00013/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc
ln ~/data/staginghistory/stage.00014//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_209501-210012.nc ~/data/staginghistory/stage.00013/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_209501-210012.nc
ln ~/data/staginghistory/stage.00014//tas_Amon_BCC-CSM2-MR_historical_r1i1p1f1_gn_185001-201412.nc ~/data/staginghistory/stage.00013/tas_Amon_BCC-CSM2-MR_historical_r1i1p1f1_gn_185001-201412.nc
ln ~/data/staginghistory/stage.00014//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc ~/data/staginghistory/stage.00013/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc
ln ~/data/staginghistory/stage.00014//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc ~/data/staginghistory/stage.00013/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc
ln ~/data/staginghistory/stage.00014//tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_185001-194912.nc ~/data/staginghistory/stage.00013/tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_185001-194912.nc
ln ~/data/staginghistory/stage.00014//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_203501-205412.nc ~/data/staginghistory/stage.00013/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_203501-205412.nc
ln ~/data/staginghistory/stage.00014//tas_Amon_BCC-CSM2-MR_ssp585_r1i1p1f1_gn_201501-210012.nc ~/data/staginghistory/stage.00013/tas_Amon_BCC-CSM2-MR_ssp585_r1i1p1f1_gn_201501-210012.nc
ln ~/data/staginghistory/stage.00014//tas_Amon_ACCESS-CM2_ssp585_r1i1p1f1_gn_201501-210012.nc ~/data/staginghistory/stage.00013/tas_Amon_ACCESS-CM2_ssp585_r1i1p1f1_gn_201501-210012.nc
ln ~/data/staginghistory/stage.00014//tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_195001-201412.nc ~/data/staginghistory/stage.00013/tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_195001-201412.nc
ln ~/data/staginghistory/stage.00014//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_205501-207412.nc ~/data/staginghistory/stage.00013/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_205501-207412.nc
ln ~/data/staginghistory/stage.00014//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00013/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
ln ~/data/staginghistory/stage.00014//tas_Amon_GFDL-ESM4_ssp585_r1i1p1f1_gr1_201501-210012.nc ~/data/staginghistory/stage.00013/tas_Amon_GFDL-ESM4_ssp585_r1i1p1f1_gr1_201501-210012.nc
ln ~/data/staginghistory/stage.00014//tas_Amon_GFDL-ESM4_historical_r1i1p1f1_gr1_195001-201412.nc ~/data/staginghistory/stage.00013/tas_Amon_GFDL-ESM4_historical_r1i1p1f1_gr1_195001-201412.nc
ln ~/data/staginghistory/stage.00014//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc ~/data/staginghistory/stage.00013/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00013/swirrl_fileinfo.json ~/data/staginghistory/stage.00013/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00014//tas_Amon_INM-CM5-0_ssp585_r1i1p1f1_gr1_201501-210012.nc ~/data/staginghistory/stage.00013/tas_Amon_INM-CM5-0_ssp585_r1i1p1f1_gr1_201501-210012.nc
ln ~/data/staginghistory/stage.00014//tas_Amon_ACCESS-CM2_historical_r1i1p1f1_gn_185001-201412.nc ~/data/staginghistory/stage.00013/tas_Amon_ACCESS-CM2_historical_r1i1p1f1_gn_185001-201412.nc
ln ~/data/staginghistory/stage.00014//tas_Amon_CMCC-ESM2_historical_r1i1p1f1_gn_185001-201412.nc ~/data/staginghistory/stage.00013/tas_Amon_CMCC-ESM2_historical_r1i1p1f1_gn_185001-201412.nc
ln ~/data/staginghistory/stage.00014//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00013/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00014//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc ~/data/staginghistory/stage.00013/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc
ln ~/data/staginghistory/stage.00014//tas_Amon_GFDL-ESM4_historical_r1i1p1f1_gr1_185001-194912.nc ~/data/staginghistory/stage.00013/tas_Amon_GFDL-ESM4_historical_r1i1p1f1_gr1_185001-194912.nc
ln ~/data/staginghistory/stage.00014//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_207501-209412.nc ~/data/staginghistory/stage.00013/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_207501-209412.nc
ln ~/data/staginghistory/stage.00014//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc ~/data/staginghistory/stage.00013/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc
ln ~/data/staginghistory/stage.00014//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc ~/data/staginghistory/stage.00013/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc
ln ~/data/staginghistory/stage.00014//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc ~/data/staginghistory/stage.00013/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc
mkdir -p ~/data/staginghistory/stage.00012
ln ~/data/staginghistory/stage.00013//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc ~/data/staginghistory/stage.00012/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc
ln ~/data/staginghistory/stage.00013//tas_Amon_CMCC-ESM2_ssp585_r1i1p1f1_gn_201501-210012.nc ~/data/staginghistory/stage.00012/tas_Amon_CMCC-ESM2_ssp585_r1i1p1f1_gn_201501-210012.nc
ln ~/data/staginghistory/stage.00013//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc ~/data/staginghistory/stage.00012/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc
ln ~/data/staginghistory/stage.00013//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc ~/data/staginghistory/stage.00012/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc
ln ~/data/staginghistory/stage.00013//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_209501-210012.nc ~/data/staginghistory/stage.00012/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_209501-210012.nc
ln ~/data/staginghistory/stage.00013//tas_Amon_BCC-CSM2-MR_historical_r1i1p1f1_gn_185001-201412.nc ~/data/staginghistory/stage.00012/tas_Amon_BCC-CSM2-MR_historical_r1i1p1f1_gn_185001-201412.nc
ln ~/data/staginghistory/stage.00013//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc ~/data/staginghistory/stage.00012/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc
ln ~/data/staginghistory/stage.00013//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc ~/data/staginghistory/stage.00012/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc
ln ~/data/staginghistory/stage.00013//tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_185001-194912.nc ~/data/staginghistory/stage.00012/tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_185001-194912.nc
ln ~/data/staginghistory/stage.00013//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_203501-205412.nc ~/data/staginghistory/stage.00012/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_203501-205412.nc
ln ~/data/staginghistory/stage.00013//tas_Amon_BCC-CSM2-MR_ssp585_r1i1p1f1_gn_201501-210012.nc ~/data/staginghistory/stage.00012/tas_Amon_BCC-CSM2-MR_ssp585_r1i1p1f1_gn_201501-210012.nc
ln ~/data/staginghistory/stage.00013//tas_Amon_ACCESS-CM2_ssp585_r1i1p1f1_gn_201501-210012.nc ~/data/staginghistory/stage.00012/tas_Amon_ACCESS-CM2_ssp585_r1i1p1f1_gn_201501-210012.nc
ln ~/data/staginghistory/stage.00013//tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_195001-201412.nc ~/data/staginghistory/stage.00012/tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_195001-201412.nc
ln ~/data/staginghistory/stage.00013//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_205501-207412.nc ~/data/staginghistory/stage.00012/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_205501-207412.nc
ln ~/data/staginghistory/stage.00013//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00012/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
ln ~/data/staginghistory/stage.00013//tas_Amon_GFDL-ESM4_ssp585_r1i1p1f1_gr1_201501-210012.nc ~/data/staginghistory/stage.00012/tas_Amon_GFDL-ESM4_ssp585_r1i1p1f1_gr1_201501-210012.nc
ln ~/data/staginghistory/stage.00013//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc ~/data/staginghistory/stage.00012/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00012/swirrl_fileinfo.json ~/data/staginghistory/stage.00012/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00013//tas_Amon_INM-CM5-0_ssp585_r1i1p1f1_gr1_201501-210012.nc ~/data/staginghistory/stage.00012/tas_Amon_INM-CM5-0_ssp585_r1i1p1f1_gr1_201501-210012.nc
ln ~/data/staginghistory/stage.00013//tas_Amon_ACCESS-CM2_historical_r1i1p1f1_gn_185001-201412.nc ~/data/staginghistory/stage.00012/tas_Amon_ACCESS-CM2_historical_r1i1p1f1_gn_185001-201412.nc
ln ~/data/staginghistory/stage.00013//tas_Amon_CMCC-ESM2_historical_r1i1p1f1_gn_185001-201412.nc ~/data/staginghistory/stage.00012/tas_Amon_CMCC-ESM2_historical_r1i1p1f1_gn_185001-201412.nc
ln ~/data/staginghistory/stage.00013//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00012/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00013//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc ~/data/staginghistory/stage.00012/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc
ln ~/data/staginghistory/stage.00013//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_207501-209412.nc ~/data/staginghistory/stage.00012/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_207501-209412.nc
ln ~/data/staginghistory/stage.00013//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc ~/data/staginghistory/stage.00012/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc
ln ~/data/staginghistory/stage.00013//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc ~/data/staginghistory/stage.00012/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc
ln ~/data/staginghistory/stage.00013//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc ~/data/staginghistory/stage.00012/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc
mkdir -p ~/data/staginghistory/stage.00011
ln ~/data/staginghistory/stage.00012//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc ~/data/staginghistory/stage.00011/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc
ln ~/data/staginghistory/stage.00012//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc ~/data/staginghistory/stage.00011/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc
ln ~/data/staginghistory/stage.00012//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc ~/data/staginghistory/stage.00011/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc
ln ~/data/staginghistory/stage.00012//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_209501-210012.nc ~/data/staginghistory/stage.00011/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_209501-210012.nc
ln ~/data/staginghistory/stage.00012//tas_Amon_BCC-CSM2-MR_historical_r1i1p1f1_gn_185001-201412.nc ~/data/staginghistory/stage.00011/tas_Amon_BCC-CSM2-MR_historical_r1i1p1f1_gn_185001-201412.nc
ln ~/data/staginghistory/stage.00012//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc ~/data/staginghistory/stage.00011/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc
ln ~/data/staginghistory/stage.00012//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc ~/data/staginghistory/stage.00011/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc
ln ~/data/staginghistory/stage.00012//tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_185001-194912.nc ~/data/staginghistory/stage.00011/tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_185001-194912.nc
ln ~/data/staginghistory/stage.00012//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_203501-205412.nc ~/data/staginghistory/stage.00011/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_203501-205412.nc
ln ~/data/staginghistory/stage.00012//tas_Amon_BCC-CSM2-MR_ssp585_r1i1p1f1_gn_201501-210012.nc ~/data/staginghistory/stage.00011/tas_Amon_BCC-CSM2-MR_ssp585_r1i1p1f1_gn_201501-210012.nc
ln ~/data/staginghistory/stage.00012//tas_Amon_ACCESS-CM2_ssp585_r1i1p1f1_gn_201501-210012.nc ~/data/staginghistory/stage.00011/tas_Amon_ACCESS-CM2_ssp585_r1i1p1f1_gn_201501-210012.nc
ln ~/data/staginghistory/stage.00012//tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_195001-201412.nc ~/data/staginghistory/stage.00011/tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_195001-201412.nc
ln ~/data/staginghistory/stage.00012//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_205501-207412.nc ~/data/staginghistory/stage.00011/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_205501-207412.nc
ln ~/data/staginghistory/stage.00012//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00011/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
ln ~/data/staginghistory/stage.00012//tas_Amon_GFDL-ESM4_ssp585_r1i1p1f1_gr1_201501-210012.nc ~/data/staginghistory/stage.00011/tas_Amon_GFDL-ESM4_ssp585_r1i1p1f1_gr1_201501-210012.nc
ln ~/data/staginghistory/stage.00012//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc ~/data/staginghistory/stage.00011/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00011/swirrl_fileinfo.json ~/data/staginghistory/stage.00011/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00012//tas_Amon_INM-CM5-0_ssp585_r1i1p1f1_gr1_201501-210012.nc ~/data/staginghistory/stage.00011/tas_Amon_INM-CM5-0_ssp585_r1i1p1f1_gr1_201501-210012.nc
ln ~/data/staginghistory/stage.00012//tas_Amon_ACCESS-CM2_historical_r1i1p1f1_gn_185001-201412.nc ~/data/staginghistory/stage.00011/tas_Amon_ACCESS-CM2_historical_r1i1p1f1_gn_185001-201412.nc
ln ~/data/staginghistory/stage.00012//tas_Amon_CMCC-ESM2_historical_r1i1p1f1_gn_185001-201412.nc ~/data/staginghistory/stage.00011/tas_Amon_CMCC-ESM2_historical_r1i1p1f1_gn_185001-201412.nc
ln ~/data/staginghistory/stage.00012//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00011/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00012//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc ~/data/staginghistory/stage.00011/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc
ln ~/data/staginghistory/stage.00012//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_207501-209412.nc ~/data/staginghistory/stage.00011/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_207501-209412.nc
ln ~/data/staginghistory/stage.00012//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc ~/data/staginghistory/stage.00011/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc
ln ~/data/staginghistory/stage.00012//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc ~/data/staginghistory/stage.00011/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc
ln ~/data/staginghistory/stage.00012//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc ~/data/staginghistory/stage.00011/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc
mkdir -p ~/data/staginghistory/stage.00010
ln ~/data/staginghistory/stage.00011//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc ~/data/staginghistory/stage.00010/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc
ln ~/data/staginghistory/stage.00011//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc ~/data/staginghistory/stage.00010/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc
ln ~/data/staginghistory/stage.00011//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc ~/data/staginghistory/stage.00010/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc
ln ~/data/staginghistory/stage.00011//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_209501-210012.nc ~/data/staginghistory/stage.00010/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_209501-210012.nc
ln ~/data/staginghistory/stage.00011//tas_Amon_BCC-CSM2-MR_historical_r1i1p1f1_gn_185001-201412.nc ~/data/staginghistory/stage.00010/tas_Amon_BCC-CSM2-MR_historical_r1i1p1f1_gn_185001-201412.nc
ln ~/data/staginghistory/stage.00011//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc ~/data/staginghistory/stage.00010/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc
ln ~/data/staginghistory/stage.00011//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc ~/data/staginghistory/stage.00010/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc
ln ~/data/staginghistory/stage.00011//tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_185001-194912.nc ~/data/staginghistory/stage.00010/tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_185001-194912.nc
ln ~/data/staginghistory/stage.00011//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_203501-205412.nc ~/data/staginghistory/stage.00010/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_203501-205412.nc
ln ~/data/staginghistory/stage.00011//tas_Amon_BCC-CSM2-MR_ssp585_r1i1p1f1_gn_201501-210012.nc ~/data/staginghistory/stage.00010/tas_Amon_BCC-CSM2-MR_ssp585_r1i1p1f1_gn_201501-210012.nc
ln ~/data/staginghistory/stage.00011//tas_Amon_ACCESS-CM2_ssp585_r1i1p1f1_gn_201501-210012.nc ~/data/staginghistory/stage.00010/tas_Amon_ACCESS-CM2_ssp585_r1i1p1f1_gn_201501-210012.nc
ln ~/data/staginghistory/stage.00011//tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_195001-201412.nc ~/data/staginghistory/stage.00010/tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_195001-201412.nc
ln ~/data/staginghistory/stage.00011//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_205501-207412.nc ~/data/staginghistory/stage.00010/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_205501-207412.nc
ln ~/data/staginghistory/stage.00011//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00010/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
ln ~/data/staginghistory/stage.00011//tas_Amon_GFDL-ESM4_ssp585_r1i1p1f1_gr1_201501-210012.nc ~/data/staginghistory/stage.00010/tas_Amon_GFDL-ESM4_ssp585_r1i1p1f1_gr1_201501-210012.nc
ln ~/data/staginghistory/stage.00011//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc ~/data/staginghistory/stage.00010/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00010/swirrl_fileinfo.json ~/data/staginghistory/stage.00010/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00011//tas_Amon_INM-CM5-0_ssp585_r1i1p1f1_gr1_201501-210012.nc ~/data/staginghistory/stage.00010/tas_Amon_INM-CM5-0_ssp585_r1i1p1f1_gr1_201501-210012.nc
ln ~/data/staginghistory/stage.00011//tas_Amon_ACCESS-CM2_historical_r1i1p1f1_gn_185001-201412.nc ~/data/staginghistory/stage.00010/tas_Amon_ACCESS-CM2_historical_r1i1p1f1_gn_185001-201412.nc
ln ~/data/staginghistory/stage.00011//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00010/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00011//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc ~/data/staginghistory/stage.00010/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc
ln ~/data/staginghistory/stage.00011//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_207501-209412.nc ~/data/staginghistory/stage.00010/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_207501-209412.nc
ln ~/data/staginghistory/stage.00011//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc ~/data/staginghistory/stage.00010/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc
ln ~/data/staginghistory/stage.00011//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc ~/data/staginghistory/stage.00010/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc
ln ~/data/staginghistory/stage.00011//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc ~/data/staginghistory/stage.00010/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc
mkdir -p ~/data/staginghistory/stage.00009
ln ~/data/staginghistory/stage.00010//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc ~/data/staginghistory/stage.00009/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc
ln ~/data/staginghistory/stage.00010//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc ~/data/staginghistory/stage.00009/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc
ln ~/data/staginghistory/stage.00010//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc ~/data/staginghistory/stage.00009/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc
ln ~/data/staginghistory/stage.00010//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_209501-210012.nc ~/data/staginghistory/stage.00009/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_209501-210012.nc
ln ~/data/staginghistory/stage.00010//tas_Amon_BCC-CSM2-MR_historical_r1i1p1f1_gn_185001-201412.nc ~/data/staginghistory/stage.00009/tas_Amon_BCC-CSM2-MR_historical_r1i1p1f1_gn_185001-201412.nc
ln ~/data/staginghistory/stage.00010//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc ~/data/staginghistory/stage.00009/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc
ln ~/data/staginghistory/stage.00010//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc ~/data/staginghistory/stage.00009/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc
ln ~/data/staginghistory/stage.00010//tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_185001-194912.nc ~/data/staginghistory/stage.00009/tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_185001-194912.nc
ln ~/data/staginghistory/stage.00010//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_203501-205412.nc ~/data/staginghistory/stage.00009/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_203501-205412.nc
ln ~/data/staginghistory/stage.00010//tas_Amon_BCC-CSM2-MR_ssp585_r1i1p1f1_gn_201501-210012.nc ~/data/staginghistory/stage.00009/tas_Amon_BCC-CSM2-MR_ssp585_r1i1p1f1_gn_201501-210012.nc
ln ~/data/staginghistory/stage.00010//tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_195001-201412.nc ~/data/staginghistory/stage.00009/tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_195001-201412.nc
ln ~/data/staginghistory/stage.00010//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_205501-207412.nc ~/data/staginghistory/stage.00009/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_205501-207412.nc
ln ~/data/staginghistory/stage.00010//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00009/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
ln ~/data/staginghistory/stage.00010//tas_Amon_GFDL-ESM4_ssp585_r1i1p1f1_gr1_201501-210012.nc ~/data/staginghistory/stage.00009/tas_Amon_GFDL-ESM4_ssp585_r1i1p1f1_gr1_201501-210012.nc
ln ~/data/staginghistory/stage.00010//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc ~/data/staginghistory/stage.00009/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00009/swirrl_fileinfo.json ~/data/staginghistory/stage.00009/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00010//tas_Amon_INM-CM5-0_ssp585_r1i1p1f1_gr1_201501-210012.nc ~/data/staginghistory/stage.00009/tas_Amon_INM-CM5-0_ssp585_r1i1p1f1_gr1_201501-210012.nc
ln ~/data/staginghistory/stage.00010//tas_Amon_ACCESS-CM2_historical_r1i1p1f1_gn_185001-201412.nc ~/data/staginghistory/stage.00009/tas_Amon_ACCESS-CM2_historical_r1i1p1f1_gn_185001-201412.nc
ln ~/data/staginghistory/stage.00010//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00009/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00010//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc ~/data/staginghistory/stage.00009/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc
ln ~/data/staginghistory/stage.00010//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_207501-209412.nc ~/data/staginghistory/stage.00009/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_207501-209412.nc
ln ~/data/staginghistory/stage.00010//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc ~/data/staginghistory/stage.00009/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc
ln ~/data/staginghistory/stage.00010//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc ~/data/staginghistory/stage.00009/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc
ln ~/data/staginghistory/stage.00010//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc ~/data/staginghistory/stage.00009/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc
mkdir -p ~/data/staginghistory/stage.00008
ln ~/data/staginghistory/stage.00009//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc ~/data/staginghistory/stage.00008/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc
ln ~/data/staginghistory/stage.00009//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc ~/data/staginghistory/stage.00008/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc
ln ~/data/staginghistory/stage.00009//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc ~/data/staginghistory/stage.00008/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc
ln ~/data/staginghistory/stage.00009//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_209501-210012.nc ~/data/staginghistory/stage.00008/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_209501-210012.nc
ln ~/data/staginghistory/stage.00009//tas_Amon_BCC-CSM2-MR_historical_r1i1p1f1_gn_185001-201412.nc ~/data/staginghistory/stage.00008/tas_Amon_BCC-CSM2-MR_historical_r1i1p1f1_gn_185001-201412.nc
ln ~/data/staginghistory/stage.00009//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc ~/data/staginghistory/stage.00008/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc
ln ~/data/staginghistory/stage.00009//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc ~/data/staginghistory/stage.00008/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc
ln ~/data/staginghistory/stage.00009//tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_185001-194912.nc ~/data/staginghistory/stage.00008/tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_185001-194912.nc
ln ~/data/staginghistory/stage.00009//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_203501-205412.nc ~/data/staginghistory/stage.00008/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_203501-205412.nc
ln ~/data/staginghistory/stage.00009//tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_195001-201412.nc ~/data/staginghistory/stage.00008/tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_195001-201412.nc
ln ~/data/staginghistory/stage.00009//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_205501-207412.nc ~/data/staginghistory/stage.00008/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_205501-207412.nc
ln ~/data/staginghistory/stage.00009//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00008/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
ln ~/data/staginghistory/stage.00009//tas_Amon_GFDL-ESM4_ssp585_r1i1p1f1_gr1_201501-210012.nc ~/data/staginghistory/stage.00008/tas_Amon_GFDL-ESM4_ssp585_r1i1p1f1_gr1_201501-210012.nc
ln ~/data/staginghistory/stage.00009//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc ~/data/staginghistory/stage.00008/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00008/swirrl_fileinfo.json ~/data/staginghistory/stage.00008/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00009//tas_Amon_INM-CM5-0_ssp585_r1i1p1f1_gr1_201501-210012.nc ~/data/staginghistory/stage.00008/tas_Amon_INM-CM5-0_ssp585_r1i1p1f1_gr1_201501-210012.nc
ln ~/data/staginghistory/stage.00009//tas_Amon_ACCESS-CM2_historical_r1i1p1f1_gn_185001-201412.nc ~/data/staginghistory/stage.00008/tas_Amon_ACCESS-CM2_historical_r1i1p1f1_gn_185001-201412.nc
ln ~/data/staginghistory/stage.00009//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00008/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00009//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc ~/data/staginghistory/stage.00008/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc
ln ~/data/staginghistory/stage.00009//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_207501-209412.nc ~/data/staginghistory/stage.00008/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_207501-209412.nc
ln ~/data/staginghistory/stage.00009//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc ~/data/staginghistory/stage.00008/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc
ln ~/data/staginghistory/stage.00009//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc ~/data/staginghistory/stage.00008/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc
ln ~/data/staginghistory/stage.00009//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc ~/data/staginghistory/stage.00008/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc
mkdir -p ~/data/staginghistory/stage.00007
ln ~/data/staginghistory/stage.00008//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc ~/data/staginghistory/stage.00007/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc
ln ~/data/staginghistory/stage.00008//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc ~/data/staginghistory/stage.00007/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc
ln ~/data/staginghistory/stage.00008//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc ~/data/staginghistory/stage.00007/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc
ln ~/data/staginghistory/stage.00008//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_209501-210012.nc ~/data/staginghistory/stage.00007/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_209501-210012.nc
ln ~/data/staginghistory/stage.00008//tas_Amon_BCC-CSM2-MR_historical_r1i1p1f1_gn_185001-201412.nc ~/data/staginghistory/stage.00007/tas_Amon_BCC-CSM2-MR_historical_r1i1p1f1_gn_185001-201412.nc
ln ~/data/staginghistory/stage.00008//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc ~/data/staginghistory/stage.00007/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc
ln ~/data/staginghistory/stage.00008//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc ~/data/staginghistory/stage.00007/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc
ln ~/data/staginghistory/stage.00008//tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_185001-194912.nc ~/data/staginghistory/stage.00007/tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_185001-194912.nc
ln ~/data/staginghistory/stage.00008//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_203501-205412.nc ~/data/staginghistory/stage.00007/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_203501-205412.nc
ln ~/data/staginghistory/stage.00008//tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_195001-201412.nc ~/data/staginghistory/stage.00007/tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_195001-201412.nc
ln ~/data/staginghistory/stage.00008//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_205501-207412.nc ~/data/staginghistory/stage.00007/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_205501-207412.nc
ln ~/data/staginghistory/stage.00008//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00007/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
ln ~/data/staginghistory/stage.00008//tas_Amon_GFDL-ESM4_ssp585_r1i1p1f1_gr1_201501-210012.nc ~/data/staginghistory/stage.00007/tas_Amon_GFDL-ESM4_ssp585_r1i1p1f1_gr1_201501-210012.nc
ln ~/data/staginghistory/stage.00008//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc ~/data/staginghistory/stage.00007/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00007/swirrl_fileinfo.json ~/data/staginghistory/stage.00007/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00008//tas_Amon_INM-CM5-0_ssp585_r1i1p1f1_gr1_201501-210012.nc ~/data/staginghistory/stage.00007/tas_Amon_INM-CM5-0_ssp585_r1i1p1f1_gr1_201501-210012.nc
ln ~/data/staginghistory/stage.00008//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00007/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00008//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc ~/data/staginghistory/stage.00007/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc
ln ~/data/staginghistory/stage.00008//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_207501-209412.nc ~/data/staginghistory/stage.00007/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_207501-209412.nc
ln ~/data/staginghistory/stage.00008//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc ~/data/staginghistory/stage.00007/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc
ln ~/data/staginghistory/stage.00008//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc ~/data/staginghistory/stage.00007/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc
ln ~/data/staginghistory/stage.00008//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc ~/data/staginghistory/stage.00007/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc
mkdir -p ~/data/staginghistory/stage.00006
ln ~/data/staginghistory/stage.00007//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc ~/data/staginghistory/stage.00006/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc
ln ~/data/staginghistory/stage.00007//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc ~/data/staginghistory/stage.00006/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc
ln ~/data/staginghistory/stage.00007//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc ~/data/staginghistory/stage.00006/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc
ln ~/data/staginghistory/stage.00007//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_209501-210012.nc ~/data/staginghistory/stage.00006/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_209501-210012.nc
ln ~/data/staginghistory/stage.00007//tas_Amon_BCC-CSM2-MR_historical_r1i1p1f1_gn_185001-201412.nc ~/data/staginghistory/stage.00006/tas_Amon_BCC-CSM2-MR_historical_r1i1p1f1_gn_185001-201412.nc
ln ~/data/staginghistory/stage.00007//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc ~/data/staginghistory/stage.00006/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc
ln ~/data/staginghistory/stage.00007//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc ~/data/staginghistory/stage.00006/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc
ln ~/data/staginghistory/stage.00007//tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_185001-194912.nc ~/data/staginghistory/stage.00006/tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_185001-194912.nc
ln ~/data/staginghistory/stage.00007//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_203501-205412.nc ~/data/staginghistory/stage.00006/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_203501-205412.nc
ln ~/data/staginghistory/stage.00007//tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_195001-201412.nc ~/data/staginghistory/stage.00006/tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_195001-201412.nc
ln ~/data/staginghistory/stage.00007//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_205501-207412.nc ~/data/staginghistory/stage.00006/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_205501-207412.nc
ln ~/data/staginghistory/stage.00007//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00006/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
ln ~/data/staginghistory/stage.00007//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc ~/data/staginghistory/stage.00006/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00006/swirrl_fileinfo.json ~/data/staginghistory/stage.00006/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00007//tas_Amon_INM-CM5-0_ssp585_r1i1p1f1_gr1_201501-210012.nc ~/data/staginghistory/stage.00006/tas_Amon_INM-CM5-0_ssp585_r1i1p1f1_gr1_201501-210012.nc
ln ~/data/staginghistory/stage.00007//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00006/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00007//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc ~/data/staginghistory/stage.00006/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc
ln ~/data/staginghistory/stage.00007//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_207501-209412.nc ~/data/staginghistory/stage.00006/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_207501-209412.nc
ln ~/data/staginghistory/stage.00007//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc ~/data/staginghistory/stage.00006/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc
ln ~/data/staginghistory/stage.00007//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc ~/data/staginghistory/stage.00006/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc
ln ~/data/staginghistory/stage.00007//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc ~/data/staginghistory/stage.00006/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc
mkdir -p ~/data/staginghistory/stage.00005
ln ~/data/staginghistory/stage.00006//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc ~/data/staginghistory/stage.00005/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc
ln ~/data/staginghistory/stage.00006//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc ~/data/staginghistory/stage.00005/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc
ln ~/data/staginghistory/stage.00006//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc ~/data/staginghistory/stage.00005/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc
ln ~/data/staginghistory/stage.00006//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_209501-210012.nc ~/data/staginghistory/stage.00005/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_209501-210012.nc
ln ~/data/staginghistory/stage.00006//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc ~/data/staginghistory/stage.00005/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc
ln ~/data/staginghistory/stage.00006//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc ~/data/staginghistory/stage.00005/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc
ln ~/data/staginghistory/stage.00006//tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_185001-194912.nc ~/data/staginghistory/stage.00005/tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_185001-194912.nc
ln ~/data/staginghistory/stage.00006//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_203501-205412.nc ~/data/staginghistory/stage.00005/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_203501-205412.nc
ln ~/data/staginghistory/stage.00006//tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_195001-201412.nc ~/data/staginghistory/stage.00005/tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_195001-201412.nc
ln ~/data/staginghistory/stage.00006//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_205501-207412.nc ~/data/staginghistory/stage.00005/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_205501-207412.nc
ln ~/data/staginghistory/stage.00006//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00005/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
ln ~/data/staginghistory/stage.00006//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc ~/data/staginghistory/stage.00005/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00005/swirrl_fileinfo.json ~/data/staginghistory/stage.00005/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00006//tas_Amon_INM-CM5-0_ssp585_r1i1p1f1_gr1_201501-210012.nc ~/data/staginghistory/stage.00005/tas_Amon_INM-CM5-0_ssp585_r1i1p1f1_gr1_201501-210012.nc
ln ~/data/staginghistory/stage.00006//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00005/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00006//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc ~/data/staginghistory/stage.00005/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc
ln ~/data/staginghistory/stage.00006//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_207501-209412.nc ~/data/staginghistory/stage.00005/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_207501-209412.nc
ln ~/data/staginghistory/stage.00006//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc ~/data/staginghistory/stage.00005/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc
ln ~/data/staginghistory/stage.00006//tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc ~/data/staginghistory/stage.00005/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc
ln ~/data/staginghistory/stage.00006//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc ~/data/staginghistory/stage.00005/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc
mkdir -p ~/data/staginghistory/stage.00004
ln ~/data/staginghistory/stage.00005//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc ~/data/staginghistory/stage.00004/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc
ln ~/data/staginghistory/stage.00005//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc ~/data/staginghistory/stage.00004/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc
ln ~/data/staginghistory/stage.00005//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc ~/data/staginghistory/stage.00004/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc
ln ~/data/staginghistory/stage.00005//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc ~/data/staginghistory/stage.00004/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc
ln ~/data/staginghistory/stage.00005//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc ~/data/staginghistory/stage.00004/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc
ln ~/data/staginghistory/stage.00005//tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_185001-194912.nc ~/data/staginghistory/stage.00004/tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_185001-194912.nc
ln ~/data/staginghistory/stage.00005//tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_195001-201412.nc ~/data/staginghistory/stage.00004/tas_Amon_INM-CM5-0_historical_r1i1p1f1_gr1_195001-201412.nc
ln ~/data/staginghistory/stage.00005//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00004/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
ln ~/data/staginghistory/stage.00005//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc ~/data/staginghistory/stage.00004/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00004/swirrl_fileinfo.json ~/data/staginghistory/stage.00004/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00005//tas_Amon_INM-CM5-0_ssp585_r1i1p1f1_gr1_201501-210012.nc ~/data/staginghistory/stage.00004/tas_Amon_INM-CM5-0_ssp585_r1i1p1f1_gr1_201501-210012.nc
ln ~/data/staginghistory/stage.00005//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00004/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00005//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc ~/data/staginghistory/stage.00004/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc
ln ~/data/staginghistory/stage.00005//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc ~/data/staginghistory/stage.00004/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc
ln ~/data/staginghistory/stage.00005//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc ~/data/staginghistory/stage.00004/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc
mkdir -p ~/data/staginghistory/stage.00003
ln ~/data/staginghistory/stage.00004//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc ~/data/staginghistory/stage.00003/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc
ln ~/data/staginghistory/stage.00004//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc ~/data/staginghistory/stage.00003/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc
ln ~/data/staginghistory/stage.00004//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc ~/data/staginghistory/stage.00003/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc
ln ~/data/staginghistory/stage.00004//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc ~/data/staginghistory/stage.00003/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc
ln ~/data/staginghistory/stage.00004//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc ~/data/staginghistory/stage.00003/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc
ln ~/data/staginghistory/stage.00004//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00003/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
ln ~/data/staginghistory/stage.00004//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc ~/data/staginghistory/stage.00003/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/swirrl_fileinfo.json ~/data/staginghistory/stage.00003/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00004//tas_Amon_INM-CM5-0_ssp585_r1i1p1f1_gr1_201501-210012.nc ~/data/staginghistory/stage.00003/tas_Amon_INM-CM5-0_ssp585_r1i1p1f1_gr1_201501-210012.nc
ln ~/data/staginghistory/stage.00004//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00003/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00004//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc ~/data/staginghistory/stage.00003/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc
ln ~/data/staginghistory/stage.00004//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc ~/data/staginghistory/stage.00003/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc
ln ~/data/staginghistory/stage.00004//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc ~/data/staginghistory/stage.00003/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc
mkdir -p ~/data/staginghistory/stage.00002
ln ~/data/staginghistory/stage.00003//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc ~/data/staginghistory/stage.00002/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc
ln ~/data/staginghistory/stage.00003//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc ~/data/staginghistory/stage.00002/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc
ln ~/data/staginghistory/stage.00003//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc ~/data/staginghistory/stage.00002/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc
ln ~/data/staginghistory/stage.00003//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc ~/data/staginghistory/stage.00002/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc
ln ~/data/staginghistory/stage.00003//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc ~/data/staginghistory/stage.00002/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc
ln ~/data/staginghistory/stage.00003//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00002/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
ln ~/data/staginghistory/stage.00003//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc ~/data/staginghistory/stage.00002/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00002/swirrl_fileinfo.json ~/data/staginghistory/stage.00002/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00003//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00002/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00003//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc ~/data/staginghistory/stage.00002/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc
ln ~/data/staginghistory/stage.00003//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc ~/data/staginghistory/stage.00002/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc
ln ~/data/staginghistory/stage.00003//tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc ~/data/staginghistory/stage.00002/tas_Amon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc
mkdir -p ~/data/staginghistory/stage.00001
ln ~/data/staginghistory/stage.00002//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00001/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00001/swirrl_fileinfo.json ~/data/staginghistory/stage.00001/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00002//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00001/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln -s ~/data/staginghistory/stage.00014 ~/data/latest
download_working_dir_data ${NOTEBOOK_URL}/api/contents
delete_notebook https://swirrl.climate4impact.eu/swirrl-api/v1.0/notebook
